<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SidemenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sidemenus')->insert([
            "module_id"=>1,
            "icon"=>"mdi-view-dashboard",
            "name"=>"Dashboard",
            "link"=>"/admin/dashboard",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>0,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>1,
            "icon"=>"mdi-settings",
            "name"=>"Settings",
            "link"=>"/admin",
            "type"=>0,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>1,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
      
        DB::table('sidemenus')->insert([
            "module_id"=>1,
            "icon"=>"mdi-format-list-checks",
            "name"=>"Roles",
            "link"=>"/admin/roles",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>1,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>1,
            "icon"=>"mdi-account-multiple",
            "name"=>"Users",
            "link"=>"/admin/users",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>2,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>1,
            "icon"=>"mdi-animation",
            "name"=>"Modules",
            "link"=>"/admin/modules",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>3,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>5,
            "icon"=>"mdi-border-left",
            "name"=>"Side Menus",
            "link"=>"/admin/sidemenus",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>4,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>6,
            "icon"=>"mdi-school",
            "name"=>"School",
            "link"=>"/admin/schools",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>5,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>7,
            "icon"=>"mdi-source-branch",
            "name"=>"Branch",
            "link"=>"/admin/branches",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>6,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>1,
            "icon"=>"mdi-settings",
            "name"=>"General Settings",
            "link"=>"/admin",
            "type"=>0,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>2,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>8,
            "icon"=>"mdi-source-branch",
            "name"=>"Cuontry",
            "link"=>"/admin/countries",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>1,
            "parentId"=>9,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>9,
            "icon"=>"mdi-source-branch",
            "name"=>"Religion",
            "link"=>"/admin/religions",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>2,
            "parentId"=>9,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>10,
            "icon"=>"mdi-source-branch",
            "name"=>"Language",
            "link"=>"/admin/languages",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>2,
            "parentId"=>9,
            "is_report"=>0,
            'created_by'=>1,
        ]);
    }
}
