name: Laravel Deployment

on:
  push:
    branches:
      - main

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  PRODUCTION_DEPLOY_BRANCH: "main"
  STAGING_DEPLOY_BRANCH: "staging"

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PRODUCTION_DEPLOY_BRANCH }}

      - name: Install Dependencies
        run: |
          composer install --no-interaction --no-ansi --no-scripts

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Deploy Code
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: '-rltgoDzvO --delete'
          local-path: '.'
          remote-path: '~/WEG/hrm'

  deploy_staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.STAGING_DEPLOY_BRANCH }}

      - name: Install Dependencies
        run: |
          composer install --no-interaction --no-ansi --no-scripts

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Deploy Code
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: '-rltgoDzvO --delete'
          local-path: '.'
          remote-path: '~/WEG/hrm_staging'
