name: Build and Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure PHP 7.4
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4 | 8.0
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist
      # - name: Build assets
      #   run: npm run build

  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: easingthemes/ssh-deploy@v2.3.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: ${{ secrets.STAGING_REMOTE_HOST }}
          remote_user: ${{ secrets.STAGING_REMOTE_USER }}
          remote_path: ${{ secrets.STAGING_REMOTE_PATH }}
          args: --exclude '.git*'
      - name: Test staging site
        run: |
          curl -s http://www.hr-staging.wegcambodia.lan | grep "Welcome to Laravel"
          # additional tests can be added here
      - name: Run additional tests
        run: vendor/bin/phpunit tests/Feature/testUserLogin.php

  deploy-production:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: easingthemes/ssh-deploy@v2.3.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: ${{ secrets.PRODUCTION_REMOTE_HOST }}
          remote_user: ${{ secrets.PRODUCTION_REMOTE_USER }}
          remote_path: ${{ secrets.PRODUCTION_REMOTE_PATH }}
          args: --exclude '.git*'
      - name: Test production site
        run: |
          curl -s http://www.hr.wegcambodia.lan | grep "Your site on product working well"
          # additional tests can be added here
